[{"user_id": 29682, "stars": [], "topic_id": 41869, "date_created": 1310589873.590482, "message": "I am running python 2.6 locally though.", "group_id": 2873, "id": 1631789}, {"user_id": 29682, "stars": [], "topic_id": 41869, "date_created": 1310589802.459919, "message": "I have just set up djcelery/celery on my app (testfuss) but as soon as I trigger an async task I am getting the following trace: http://dpaste.de/nBgW/", "group_id": 2873, "id": 1631776}, {"user_id": 29682, "stars": [], "topic_id": 41869, "date_created": 1310589864.4959691, "message": "Everything is working locally when using djkombu's DB transport, and running a celeryd", "group_id": 2873, "id": 1631787}, {"user_id": 29682, "stars": [], "topic_id": 41869, "date_created": 1310592266.1000741, "message": "cool, ta", "group_id": 2873, "id": 1632011}, {"user_id": 29682, "stars": [], "topic_id": 41869, "date_created": 1310594221.627655, "message": "after running it the first time it actually started working", "group_id": 2873, "id": 1632333}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310591630.7849391, "message": "@bradwhittington Ah yes, that's a problem with the requirements on celery not being strict enough", "group_id": 2873, "id": 1631955}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310591711.410985, "message": "you'll need to add redis>=2.4.5 to your requirements", "group_id": 2873, "id": 1631960}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310594873.816278, "message": "though on your development machine, it works as you described it", "group_id": 2873, "id": 1632425}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310595012.5257709, "message": "aha, just found the issue in our uploader", "group_id": 2873, "id": 1632452}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310595020.496352, "message": "had the wrong condition in an if clause, typical", "group_id": 2873, "id": 1632455}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310595071.204694, "message": "indeed, it was a hangover from the old way we tested celery's existence", "group_id": 2873, "id": 1632463}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310595080.964066, "message": "I think we have a #HACK somewhere, still", "group_id": 2873, "id": 1632469}, {"user_id": 29682, "stars": [], "topic_id": 41869, "date_created": 1310595037.225625, "message": "better than #TODO: make work!!!", "group_id": 2873, "id": 1632458}, {"user_id": 29682, "stars": [], "topic_id": 41869, "date_created": 1310595266.447578, "message": "\"Do you exist?\" 'Not sure' \"Lulz\" 'Lulz'.", "group_id": 2873, "id": 1632503}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310594910.4130559, "message": "if you used run_command, then obviously it would keep running, but that's not how we run celery round these parts", "group_id": 2873, "id": 1632429}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310595532.895664, "message": "alright, new uploader code in place", "group_id": 2873, "id": 1632549}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310594730.205096, "message": "I suspect there's a hole in our new uploader where it forgot to assign you one, so I'll get that fixes", "group_id": 2873, "id": 1632396}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310594732.1051171, "message": "*fixed", "group_id": 2873, "id": 1632397}, {"user_id": 29682, "stars": [], "topic_id": 41869, "date_created": 1310594821.610271, "message": "cool beans. so in the current set up of a manual runner...if I add new @task functions, or change existing ones, the worker won't be rebooted, and won't have the new functions, right? (Just checking if my understanding of celery is correct)", "group_id": 2873, "id": 1632414}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310594643.08215, "message": "oh", "group_id": 2873, "id": 1632378}, {"user_id": 29682, "stars": [], "topic_id": 41869, "date_created": 1310594882.3192389, "message": "right.", "group_id": 2873, "id": 1632427}, {"user_id": 29682, "stars": [], "topic_id": 41869, "date_created": 1310594723.6350369, "message": "yah, see that now", "group_id": 2873, "id": 1632394}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310594665.903533, "message": "hmm, has the same lack of a worker assigned", "group_id": 2873, "id": 1632383}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310594848.672869, "message": "actually, the worker is rebooted whenever the code version changes, i.e. on every upload", "group_id": 2873, "id": 1632421}, {"user_id": 29682, "stars": [], "topic_id": 41869, "date_created": 1310594200.8797309, "message": "Okay, that worked, but it seems like the celeryd workers only started up when I ran:", "group_id": 2873, "id": 1632329}, {"user_id": 29682, "stars": [], "topic_id": 41869, "date_created": 1310594205.6454811, "message": "bradley@dev:~/src/git/lessfuss/TaskMaster/taskmaster$ epio django celeryd -- -l info\n\n\nep.io: Error: Connection to runner timed out.\nConnection to upload.ep.io closed.\nbradley@dev:~/src/git/lessfuss/TaskMaster/taskmaster$ epio django celeryd -- -l info\n[2011-07-13 23:55:22,993: WARNING/MainProcess]  \n", "group_id": 2873, "id": 1632330}, {"user_id": 29682, "stars": [], "topic_id": 41869, "date_created": 1310594429.102325, "message": "exiting the process nabs all the workers, and it stops processing the queue :/", "group_id": 2873, "id": 1632354}, {"user_id": 29682, "stars": [], "topic_id": 41869, "date_created": 1310594626.8723359, "message": "oh, sorry, this would have been running in testfuss", "group_id": 2873, "id": 1632377}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310594604.1549959, "message": "hmm, yes, taskmaster hasn't been assigned a celeryd piece (i.e. told to run it all the time)", "group_id": 2873, "id": 1632371}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310594654.0101011, "message": "I was going off the directory name. Hold on then.", "group_id": 2873, "id": 1632380}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310594675.7315071, "message": "is this a new app, or one that was around before the migration?", "group_id": 2873, "id": 1632385}, {"user_id": 29682, "stars": [], "topic_id": 41869, "date_created": 1310594976.601825, "message": "cool :) Django and ep.io are rapidly becoming my coding mecha-suits. Thanks for the hard work, it is seriously awesome so far.", "group_id": 2873, "id": 1632443}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310595096.4352579, "message": "but it's probably the bit that stops Django, psycopg2 and eventlet having a war", "group_id": 2873, "id": 1632473}, {"user_id": 29682, "stars": [], "topic_id": 41869, "date_created": 1310594697.5252559, "message": "prior to migration, first time using celery and redis", "group_id": 2873, "id": 1632387}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310594713.232106, "message": "alright, I've manually assigned a worker to it, should be coming up now", "group_id": 2873, "id": 1632389}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310595567.9534211, "message": "of course, it'll need changing when we release the new, \"run arbitary daemons\" code, but hey", "group_id": 2873, "id": 1632560}, {"user_id": 8740, "stars": [], "topic_id": 41869, "date_created": 1310595543.509016, "message": "it'll now actually create and delete celery instance markers", "group_id": 2873, "id": 1632552}, {"user_id": 29682, "stars": [], "topic_id": 41869, "date_created": 1310595590.4670539, "message": "Sweet, look forward to it Just Working\u2122 when i deploy to 'production'", "group_id": 2873, "id": 1632568}]