[{"user_id": 5029, "stars": [], "topic_id": 21585, "date_created": 1303889090.3710639, "message": "there is a trac-creds file in this project that is ignored using .gitignore, and it was not uploaded to my application (I could see that in the console log)", "group_id": 2873, "id": 822976}, {"user_id": 5029, "stars": [], "topic_id": 21585, "date_created": 1303889106.173274, "message": "just for the upload, I removed .gitignore, and then it worked", "group_id": 2873, "id": 822977}, {"user_id": 5029, "stars": [], "topic_id": 21585, "date_created": 1303889033.5923669, "message": "Yesterday, I uploaded a modified version of the django dev dashboard to ep.io (see http://sparkboard.ep.io) and as I wrote in a wrong topic, I think I have seen a bug :", "group_id": 2873, "id": 822973}, {"user_id": 5029, "stars": [], "topic_id": 21585, "date_created": 1303889182.3089149, "message": "BTW, I really love the system.", "group_id": 2873, "id": 823000}, {"user_id": 5029, "stars": [], "topic_id": 21585, "date_created": 1303889164.921838, "message": "Alex Gaynor told me yesterday that it was known, but I do not think this is documented somewhere", "group_id": 2873, "id": 822995}, {"user_id": 8740, "stars": [], "topic_id": 21585, "date_created": 1303895500.2020531, "message": "@madewulf That was fixed in the 0.2.5 release of the client: http://www.ep.io/docs/client/#id5 - are you up to date?", "group_id": 2873, "id": 823690}, {"user_id": 5029, "stars": [], "topic_id": 21585, "date_created": 1303904147.9632571, "message": "No, 0.2.1", "group_id": 2873, "id": 824492}, {"user_id": 5029, "stars": [], "topic_id": 21585, "date_created": 1303904153.0025401, "message": "Thanks", "group_id": 2873, "id": 824494}, {"user_id": 5029, "stars": [], "topic_id": 21585, "date_created": 1303904151.7248149, "message": "I will update", "group_id": 2873, "id": 824493}, {"user_id": 5029, "stars": [], "topic_id": 21585, "date_created": 1303904122.8193619, "message": "Ah, maybe not", "group_id": 2873, "id": 824489}]