[{"user_id": 39067, "stars": [], "topic_id": 43011, "date_created": 1312050497.247349, "message": "C'est quelque chose de normal. Si une exception bubble up jusqu'au top level sans \u00eatre attrap\u00e9e c'est ce que \u00e7a fait: http://nodejs.org/docs/v0.5.2/api/all.html#event_uncaughtException_", "group_id": 11080, "id": 1755375}, {"user_id": 39067, "stars": [], "topic_id": 43011, "date_created": 1312050351.2289879, "message": "Quelqu'un disait que les erreurs ferme le serveur sans rien dire", "group_id": 11080, "id": 1755367}, {"user_id": 39069, "stars": [], "topic_id": 43011, "date_created": 1312051900.5734861, "message": "c'est donc la responsabilit\u00e9 du dev. de mettre des try catch aux endroits sensibles dans le code", "group_id": 11080, "id": 1755451}, {"user_id": 38984, "stars": [], "topic_id": 43011, "date_created": 1312147940.5484431, "message": "C'est ce que je me disais aussi. Dans l'fond, node c'est juste le serveur. Dans un stack habituel, on utilise un framework par-dessus le serveur et c'est lui qui attrappe les exceptions.", "group_id": 11080, "id": 1760677}, {"user_id": 39067, "stars": [], "topic_id": 43011, "date_created": 1312196278.5262151, "message": "Par contre, il y a un mode debug qui permet de suivre le stack trace. C'est quand m\u00eame bien fait!", "group_id": 11080, "id": 1764837}]