[{"user_id": 275, "stars": [], "topic_id": 34254, "date_created": 1304870493.1553731, "message": "I'm getting this error when I boot up celeryd via manage.py", "group_id": 81, "id": 958173}, {"user_id": 275, "stars": [], "topic_id": 34254, "date_created": 1304870502.7155271, "message": "https://gist.github.com/961455", "group_id": 81, "id": 958176}, {"user_id": 275, "stars": [], "topic_id": 34254, "date_created": 1304870532.085876, "message": "it looks like it gets all ready to go, then explodes for some reason I have not yet determined.", "group_id": 81, "id": 958180}, {"user_id": 275, "stars": [], "topic_id": 34254, "date_created": 1304870577.0746469, "message": "and redis is the latest version (I believe, I can't figure out how to ask redis-server what version is running)", "group_id": 81, "id": 958185}, {"user_id": 275, "stars": [], "topic_id": 34254, "date_created": 1304870547.2740901, "message": "redis-server is running (I can use redis-cli to talk to it)", "group_id": 81, "id": 958181}, {"user_id": 5980, "stars": [{"date_created": 1304986638.1928899, "user_id": 141}], "topic_id": 34254, "date_created": 1304879494.8718159, "message": "I'm not a Celery expert, but it looks like the error (unknown command SUBSCRIBE) is coming from Redis itself, which suggest you might be running an old version. Use", "group_id": 81, "id": 959340}, {"user_id": 5980, "stars": [], "topic_id": 34254, "date_created": 1304879510.767277, "message": "oops. use \"redis-cli info\" to check your version (should be the first item in the list)", "group_id": 81, "id": 959341}, {"user_id": 275, "stars": [{"date_created": 1304986649.3103781, "user_id": 141}, {"date_created": 1305039595.9255869, "user_id": 257}], "topic_id": 34254, "date_created": 1304953058.383884, "message": "looks like i had to uninstall the redis 1.2 package from apt, and re-install 2.2.6 from source", "group_id": 81, "id": 972661}]