[{"user_id": 12716, "stars": [], "topic_id": 37182, "date_created": 1306599655.4914351, "message": "I also tried django_extensions dumpscript without success.", "group_id": 81, "id": 1213016}, {"user_id": 12716, "stars": [], "topic_id": 37182, "date_created": 1306599628.9729171, "message": "Does anyone have recommendations on how to export and import the auth? Exporting a fixture is easy. However trying to import the fixture into a new database fails with Integrity errors. I've tried importing individual models auth.user, auth.groups, auth.permissions and contentypes with no success.", "group_id": 81, "id": 1213012}, {"user_id": 27489, "stars": [], "topic_id": 37182, "date_created": 1306603655.2533181, "message": "Have you tried using the -n (--natural) argument?", "group_id": 81, "id": 1213345}, {"user_id": 12716, "stars": [], "topic_id": 37182, "date_created": 1306606452.574712, "message": "@fabianbuechler no. will try now", "group_id": 81, "id": 1213507}, {"user_id": 12716, "stars": [], "topic_id": 37182, "date_created": 1306607498.960237, "message": "I didn't work in the current state of the db but the import may work if I load those first before the apps data. I have a work around I'm using for now. Thanks @fabianbuechler", "group_id": 81, "id": 1213603}, {"user_id": 27489, "stars": [], "topic_id": 37182, "date_created": 1306613103.155349, "message": "@citadelgrad, you're welcome. In case you want some docs on this: https://docs.djangoproject.com/en/dev/topics/serialization/#natural-keys and https://docs.djangoproject.com/en/dev/ref/django-admin/#django-admin-option---natural might be helpful.", "group_id": 81, "id": 1213815}]