[{"user_id": 32294, "stars": [], "topic_id": 46637, "date_created": 1318864393.5243609, "message": "I am getting File \"/opt/django-dpp/dpp-externals/django/http/multipartparser.py\" in read\n  405.         return self._file.read(num_bytes)\n\nException Type: IOError at ...upload...\nException Value: request data read error\nDefinetively the client is not stopping the upload - it happens between 2 and 3 minutes upload time.", "group_id": 81, "id": 2368598}, {"user_id": 5981, "stars": [], "topic_id": 46637, "date_created": 1318872544.866524, "message": "You know I've been seeing the same thing, but I haven't been getting any feedback about failures from the users, so I wasn't quite sure what to make of it. For the most part, I see this on uploads that are not large (4-5M) so I'm left scratching my head.", "group_id": 81, "id": 2369247}, {"user_id": 32294, "stars": [], "topic_id": 46637, "date_created": 1318924673.0467629, "message": "In our case the upload time is the critical factor. size varies from 1mb to 130mb, depending on the connection speed.", "group_id": 81, "id": 2374713}, {"user_id": 32294, "stars": [], "topic_id": 46637, "date_created": 1318924707.103323, "message": "In our case the upload time is the critical factor. size varies from 1mb to 130mb, depending on the connection speed.", "group_id": 81, "id": 2374715}, {"user_id": 32294, "stars": [], "topic_id": 46637, "date_created": 1318924735.4015479, "message": "Apache version is 2.2.21\nmod_wsgi is 2.3\npython is 2.5.5\nsolaris 10 on Intel\n", "group_id": 81, "id": 2374717}, {"user_id": 28981, "stars": [], "topic_id": 46637, "date_created": 1318925721.839397, "message": "This was my original question: http://stackoverflow.com/questions/3823280/ioerror-request-data-read-error", "group_id": 81, "id": 2374758}, {"user_id": 28981, "stars": [], "topic_id": 46637, "date_created": 1318925623.0547211, "message": "Are you using boto by any chance?", "group_id": 81, "id": 2374752}, {"user_id": 28981, "stars": [], "topic_id": 46637, "date_created": 1318925662.9913371, "message": "I had the same issues last year and gave me quite hell. Simply adding a timeout to the http socket made it work", "group_id": 81, "id": 2374755}, {"user_id": 32294, "stars": [], "topic_id": 46637, "date_created": 1319100170.87323, "message": "this has not solved our problem....", "group_id": 81, "id": 2390656}]