[{"user_id": 3580, "stars": [], "topic_id": 36017, "date_created": 1305841626.178086, "message": "    from django.conf import settings\nImportError: No module named conf\n", "group_id": 81, "id": 1116979}, {"user_id": 3580, "stars": [], "topic_id": 36017, "date_created": 1305841674.470315, "message": "I've run into this before.. and I think it had something to do with circular imports or something.. any suggestions on how to chase this down? basically once I go to import a views module, it imports something that 'from django.conf import settings' and all hell breaks loose.", "group_id": 81, "id": 1116986}, {"user_id": 3580, "stars": [{"date_created": 1306258293.445534, "user_id": 141}], "topic_id": 36017, "date_created": 1305842538.2309699, "message": "doh! my bad. relative modules are tricky. on of my team members added a django.py file to a util module of ours :)", "group_id": 81, "id": 1117191}, {"user_id": 12843, "stars": [], "topic_id": 36017, "date_created": 1305851304.3952141, "message": "I thought I could do something like sys.path.remove('.') to stop it from importing from the current dir - but I don't have '.' in sys.path for some reason (or anything else that looks like it's the bad path)", "group_id": 81, "id": 1118163}, {"user_id": 12843, "stars": [], "topic_id": 36017, "date_created": 1305851210.731576, "message": "gah, I'm chasing the exact same thing right now", "group_id": 81, "id": 1118159}, {"user_id": 12843, "stars": [], "topic_id": 36017, "date_created": 1305851225.306529, "message": "we have a django dir in our project I can't get rid of :(", "group_id": 81, "id": 1118160}, {"user_id": 12843, "stars": [], "topic_id": 36017, "date_created": 1305851337.012152, "message": "but I can tell this is the root of the issue because import django;django.__file__ shows it's the wrong django", "group_id": 81, "id": 1118164}, {"user_id": 1127, "stars": [{"date_created": 1305870160.5800469, "user_id": 4748}, {"date_created": 1305876673.5662169, "user_id": 1736}, {"date_created": 1305910582.2626939, "user_id": 3580}, {"date_created": 1306243883.8728881, "user_id": 927}, {"date_created": 1306258301.8660469, "user_id": 141}], "topic_id": 36017, "date_created": 1305868600.961329, "message": "from __future__ import absolute_path", "group_id": 81, "id": 1120797}, {"user_id": 1127, "stars": [], "topic_id": 36017, "date_created": 1305868624.923903, "message": "or __import__('django').django", "group_id": 81, "id": 1120803}, {"user_id": 4748, "stars": [], "topic_id": 36017, "date_created": 1305870189.4632881, "message": "@zeeg This is pretty much the most concise argument I've seen for absolute path imports.", "group_id": 81, "id": 1121000}, {"user_id": 3580, "stars": [], "topic_id": 36017, "date_created": 1305910642.8050089, "message": "Thanks @zeeg.. I wasn't aware of the absolute_path import. That's huge.", "group_id": 81, "id": 1127863}, {"user_id": 1127, "stars": [], "topic_id": 36017, "date_created": 1305919534.6333129, "message": "i refuse to name my modules something like \"djangocontrib\", but rather something like \"contrib.django\", so I use it fairly often :)", "group_id": 81, "id": 1129378}]