[{"user_id": 5250, "stars": [], "topic_id": 11027, "date_created": 1299365747.0190451, "message": "I am using django-social-auth to let people log in using Twitter. I would like to be able to take them back to the page they asked for in the first place, but so far as I can tell it is set up to return to a page specified in settings.py. Am I missing something?", "group_id": 81, "id": 277893}, {"user_id": 7179, "stars": [], "topic_id": 11027, "date_created": 1299368103.04052, "message": "I think django-social-auth works in the same way than Django's auth, when you pass 'next' as GET parameter to the login URL and the current URL as the value it redirects to the current page. \n\nFor example:\n<a href=\"/login/?next={{request.path}}\">", "group_id": 81, "id": 277948}, {"user_id": 7179, "stars": [], "topic_id": 11027, "date_created": 1299368119.1672609, "message": "As per this issue, they support the next param: https://github.com/omab/django-social-auth/issues/32", "group_id": 81, "id": 277949}, {"user_id": 5250, "stars": [], "topic_id": 11027, "date_created": 1299369091.0371261, "message": "It refers to a line 95 which reads: \"return HttpResponseServerError('Incorrect authentication service')\". I don't see the connection between this and the 'next' parameter. But I guess I can give it a go anyway.", "group_id": 81, "id": 277991}, {"user_id": 7179, "stars": [], "topic_id": 11027, "date_created": 1299372323.8898039, "message": "yes, it's probably an old reference.. try and tell us", "group_id": 81, "id": 278097}, {"user_id": 12067, "stars": [], "topic_id": 11027, "date_created": 1299373840.3410881, "message": "Looks like it's i line 97 now. REDIRECT_FIELD_NAME is the same Django setting that contrib.auth uses which is by default \"next\".", "group_id": 81, "id": 278147}, {"user_id": 719, "stars": [], "topic_id": 11027, "date_created": 1299379530.6149149, "message": "I'll go sit in my \"don't be so chatty\" corner.", "group_id": 81, "id": 278309}, {"user_id": 719, "stars": [], "topic_id": 11027, "date_created": 1299380433.481895, "message": "See you around then. :)", "group_id": 81, "id": 278395}, {"user_id": 719, "stars": [], "topic_id": 11027, "date_created": 1299379493.7927761, "message": "D'oh... the blog post covers that. :)", "group_id": 81, "id": 278307}, {"user_id": 719, "stars": [], "topic_id": 11027, "date_created": 1299380343.0999451, "message": "Cool.", "group_id": 81, "id": 278387}, {"user_id": 6396, "stars": [], "topic_id": 11027, "date_created": 1299379542.869617, "message": "It's actually been updated since I wrote that; the new code uses urlparse instead of a regex check. See here: http://code.djangoproject.com/browser/django/trunk/django/contrib/auth/views.py#L37", "group_id": 81, "id": 278311}, {"user_id": 6396, "stars": [], "topic_id": 11027, "date_created": 1299379254.305629, "message": "Hmm, they're not sanitising their redirects...", "group_id": 81, "id": 278283}, {"user_id": 6396, "stars": [], "topic_id": 11027, "date_created": 1299379267.0375869, "message": "Not the most dangerous of things but incredibly useful to any phisher.", "group_id": 81, "id": 278285}, {"user_id": 6396, "stars": [], "topic_id": 11027, "date_created": 1299379276.6632061, "message": "I've forked and fixed that here: https://github.com/djm/django-social-auth/commit/32a67fa2a751b59d6c775f8f201981c4a27b2610", "group_id": 81, "id": 278286}, {"user_id": 6396, "stars": [], "topic_id": 11027, "date_created": 1299379279.9288039, "message": "Will pull request now..", "group_id": 81, "id": 278287}, {"user_id": 6396, "stars": [], "topic_id": 11027, "date_created": 1299379301.0454099, "message": "More on that danger here: www.djm.org.uk/djangos-little-protections-word-redirect-dangers/", "group_id": 81, "id": 278289}, {"user_id": 719, "stars": [], "topic_id": 11027, "date_created": 1299379443.6997399, "message": "Yeah, a similar issue was fixed in core recently.", "group_id": 81, "id": 278302}, {"user_id": 6396, "stars": [], "topic_id": 11027, "date_created": 1299379570.797878, "message": "and I like the chatty corner :)", "group_id": 81, "id": 278316}, {"user_id": 719, "stars": [], "topic_id": 11027, "date_created": 1299380069.5338221, "message": "@djm (Random) Just noticed you're based in London. Do you ever drop by the London Python code dojo events?", "group_id": 81, "id": 278365}, {"user_id": 6396, "stars": [], "topic_id": 11027, "date_created": 1299380139.980562, "message": "@micrypt Not yet, but been meaning too for a while now. Been to a couple of DJUGLs though! When's the next one?", "group_id": 81, "id": 278369}, {"user_id": 6396, "stars": [], "topic_id": 11027, "date_created": 1299380154.1103871, "message": "Pull request for the sec. fix here btw: https://github.com/omab/django-social-auth/pull/38", "group_id": 81, "id": 278372}, {"user_id": 6396, "stars": [], "topic_id": 11027, "date_created": 1299380332.4506769, "message": "Yeh they have been recently. I'll try and get down to the next dojo though, will keep an eye out.", "group_id": 81, "id": 278386}, {"user_id": 719, "stars": [], "topic_id": 11027, "date_created": 1299380241.6410279, "message": "The last one was on the 3rd of March. I don't think there's a date set for the next yet. DJULs are good.. if a tad inconsistent. :(", "group_id": 81, "id": 278380}, {"user_id": 6396, "stars": [], "topic_id": 11027, "date_created": 1299380643.9973819, "message": "Indeed, look forward to it. :)", "group_id": 81, "id": 278419}]