[{"user_id": 28981, "stars": [], "topic_id": 44446, "date_created": 1314281161.6685791, "message": "But figured maybe this was a better place for general discussion.", "group_id": 5196, "id": 1958899}, {"user_id": 28981, "stars": [], "topic_id": 44446, "date_created": 1314281149.937453, "message": "I'd created an issue here: https://github.com/omab/django-social-auth/issues/131", "group_id": 5196, "id": 1958897}, {"user_id": 28981, "stars": [], "topic_id": 44446, "date_created": 1314281273.1877401, "message": "Is anyone else using social_auth in production, i keep getting integrity errors on creation of UserSocialAuth. And guess that can only happen if get_or_create creates a duplicate?, since i'd made that change to see if that fixed the issue.", "group_id": 5196, "id": 1958909}]