[{"user_id": 29686, "stars": [], "topic_id": 35114, "date_created": 1305286288.2195561, "message": "none of my apps seem to upload anymore all of them timing out at the \"ep.io: Getting service configuration...\" step...", "group_id": 2873, "id": 1039735}, {"user_id": 29686, "stars": [], "topic_id": 35114, "date_created": 1305286354.7128861, "message": "with this error: \"ep.io: Bundling error!\nep.io: Timeout waiting for service responses for uid, postgres\nTo vcs@upload.ep.io:tinodriwa\n * [new branch]      master -> master\nerror: failed to push some refs to 'vcs@upload.ep.io:tinodriwa'", "group_id": 2873, "id": 1039745}, {"user_id": 21184, "stars": [], "topic_id": 35114, "date_created": 1305369725.1714931, "message": "@tijs Yes I had the same problem. Though it works again as of now. Ben Firsh wrote that they had a minor Postgres issue, that's resolved now", "group_id": 2873, "id": 1051319}, {"user_id": 8740, "stars": [], "topic_id": 35114, "date_created": 1305394521.9262209, "message": "Yes, the postgres service was failing to allocate new apps' databases; I've been away the last two days, and Ben didn't realise until yesterday - sorry about that! We'll work on making sure he gets more of the notifications.", "group_id": 2873, "id": 1053666}, {"user_id": 35238, "stars": [], "topic_id": 35114, "date_created": 1308976315.0486081, "message": "Having this same issue now, \"Timeout waiting for service responses for uid, postgres\"...", "group_id": 2873, "id": 1482790}, {"user_id": 8740, "stars": [], "topic_id": 35114, "date_created": 1308990019.2099459, "message": "@rain_zuko should be fixed now", "group_id": 2873, "id": 1483318}, {"user_id": 38112, "stars": [], "topic_id": 35114, "date_created": 1310718453.24471, "message": "ep.io: Bundling error!\nep.io: There is no available service called 'postgres'.\n", "group_id": 2873, "id": 1643824}, {"user_id": 38112, "stars": [], "topic_id": 35114, "date_created": 1310718467.153306, "message": "Getting this error trying to upload a new app", "group_id": 2873, "id": 1643826}, {"user_id": 29682, "stars": [], "topic_id": 35114, "date_created": 1310719477.754082, "message": "Having an issue with already deployed apps as well, and trying to upload again is getting that same error ^^^", "group_id": 2873, "id": 1643872}, {"user_id": 36171, "stars": [], "topic_id": 35114, "date_created": 1310721013.164258, "message": "All my apps have become unavailable. Can't load any from the browser, and cant shell or upload or pretty much anything. In fact, the only thing I _can_ get is: https://www.ep.io/control/ - where i can at least see that my apps are there", "group_id": 2873, "id": 1643927}, {"user_id": 29686, "stars": [], "topic_id": 35114, "date_created": 1310719204.1719649, "message": "yeah getting the same error. this is the worst timing.", "group_id": 2873, "id": 1643867}, {"user_id": 36171, "stars": [], "topic_id": 35114, "date_created": 1310721345.686152, "message": "heh. Just as I post it they fix it ;)", "group_id": 2873, "id": 1643949}, {"user_id": 8740, "stars": [], "topic_id": 35114, "date_created": 1310726362.9726419, "message": "Yes, sorry everyone, postgres service locked up (had it crashed it would have been restarted, but instead it just sat there)", "group_id": 2873, "id": 1644224}, {"user_id": 8740, "stars": [], "topic_id": 35114, "date_created": 1310726380.267107, "message": "I've just finished writing a whole new suite of nagios checks to make sure the processes still send heartbeats", "group_id": 2873, "id": 1644228}, {"user_id": 12716, "stars": [], "topic_id": 35114, "date_created": 1310860430.2300961, "message": "@andrewgodwin Recently uploaded apps don't appear to be initializing. Help! My app is hh_dev.ep.io", "group_id": 2873, "id": 1654551}, {"user_id": 8740, "stars": [], "topic_id": 35114, "date_created": 1310896636.649657, "message": "@citadelgrad Should be fixed now; what error did you get? Our logs only show it being loaded, and then shut down due to inactivity a while later", "group_id": 2873, "id": 1656192}, {"user_id": 12716, "stars": [], "topic_id": 35114, "date_created": 1310932110.433625, "message": "@andrewgodwin Thanks for your help. No error messages and I was my fault because I hadn't configured something correctly.", "group_id": 2873, "id": 1658216}, {"user_id": 8740, "stars": [], "topic_id": 35114, "date_created": 1310937336.770124, "message": "@citadelgrad Ah, alright. If there's some way we could have provided you with a better error message, please say!", "group_id": 2873, "id": 1658773}, {"user_id": 38267, "stars": [], "topic_id": 35114, "date_created": 1310988592.3703151, "message": "I think a similar problem is happening again... getting a \"ep.io: There is no available service called 'core'.\" when uploading an already existing app.", "group_id": 2873, "id": 1661689}, {"user_id": 29682, "stars": [], "topic_id": 35114, "date_created": 1310989225.4266939, "message": "Getting \"ep.io: Lost connection to runner; command exiting prematurely.\" when trying to upload an existing app", "group_id": 2873, "id": 1661738}, {"user_id": 29686, "stars": [], "topic_id": 35114, "date_created": 1310995005.0004261, "message": "got the same 'no core service' error but that's fixed now", "group_id": 2873, "id": 1662214}]